export const CLIENT_FACTS = {
  brand: "MSRTC Media Network",
  implementationLine: "Implemented by KIPL",
  implementer: "Krish Intratrade Pvt. Ltd. (KIPL)",
  districts: "36",
  busStations: "562+",
  buses: "14,199+",
  upcomingFleet: "8,000",
  dailyReach: "6.5M+",
  grabHandles: "1,70,388 Grab Handles",
  grabHandlesLogic: "12 per bus",
  hoardings: "2,100",
  digitalHoardings: "approx. 500",
  screens: "1,686 screens",
  busStandBrandingStart: "16.05.2026",
  socialMediaStart: "16.05.2026",
  digitalHoardingsStart: "16.08.2026",
  physicalTimeline:
    "Physical media can go live in 48–72 hours after approval, printing, and mounting.",
  digitalTimeline:
    "Digital campaigns can go live quickly depending on media availability and approval.",
  kiplExperience: "14+ years",
  kiplEmployees: "225 Employees",
  companyDistricts: "36 Districts",
  monitoring: "Centralized Heartbeat Monitoring",
  contactEmail: "contactus@kiploutdoormedia.com",
  contactPhoneRaw: "+91 9850999958",
  contactPhoneDisplay: "+91 98509 99958",
  whatsappNumber: "919850999958",
  whatsappMessage:
    "Hey! I just visited your website and would love to know more about the media inventory of KIPL",
  hiring:
    "We’re Hiring! Contact us to join us by sharing your CV via Mail/Contact Number.",
} as const;

export const TRUST_STATS = [
  { value: CLIENT_FACTS.busStations, label: "Stations" },
  { value: CLIENT_FACTS.buses, label: "Buses" },
  { value: CLIENT_FACTS.districts, label: "Districts" },
  { value: CLIENT_FACTS.dailyReach, label: "Daily Reach" },
] as const;

export type InventoryStatus = "Live Now" | "Launching Soon" | "Subject to Clearance / Fleet Rollout" | "Coming in Phases";
export type InventoryCategory = "Station Media" | "Bus Media" | "Digital Media" | "Audio Media" | "Social Media";

export const MEDIA_INVENTORY = [
  {
    slug: "bus-stand-branding",
    name: "Bus Stand Branding",
    status: "Live Now",
    category: "Station Media",
    startDate: CLIENT_FACTS.busStandBrandingStart,
    bestUse: "High-frequency station visibility for commuters with repeat dwell-time exposure.",
    reporting: "GPS-enabled start photos, end photos, and installation proof.",
  },
  {
    slug: "social-media-advertising",
    name: "Social Media Advertising",
    status: "Live Now",
    category: "Social Media",
    startDate: CLIENT_FACTS.socialMediaStart,
    bestUse: "Extend transit campaigns into digital channels for awareness and recall.",
    reporting: "Campaign analytics and performance reporting where applicable.",
  },
  {
    slug: "digital-hoardings",
    name: "Digital Hoardings",
    status: "Launching Soon",
    category: "Digital Media",
    startDate: CLIENT_FACTS.digitalHoardingsStart,
    quantity: CLIENT_FACTS.digitalHoardings,
    bestUse: "Large-format programmable visibility at high-traffic transit locations.",
    reporting: "Digital screen logs and display count access where applicable.",
  },
  {
    slug: "grab-handles",
    name: "Grab Handles",
    status: "Subject to Clearance / Fleet Rollout",
    category: "Bus Media",
    quantity: CLIENT_FACTS.grabHandles,
    note: CLIENT_FACTS.grabHandlesLogic,
    bestUse: "Eye-level in-bus recall for captive passengers across route journeys.",
    reporting: "Installation proof and GPS-enabled placement photographs.",
  },
  {
    slug: "hoardings",
    name: "Hoardings",
    status: "Coming in Phases",
    category: "Station Media",
    quantity: CLIENT_FACTS.hoardings,
    bestUse: "Large-format station and transit visibility for brand salience.",
    reporting: "GPS-enabled installation proof and campaign execution reports.",
  },
  {
    slug: "screens-led-screens",
    name: "Screens / LED Screens",
    status: "Subject to Clearance / Fleet Rollout",
    category: "Digital Media",
    quantity: CLIENT_FACTS.screens,
    bestUse: "Motion-led message delivery inside approved screen environments.",
    reporting: "Digital screen logs and display count access where applicable.",
  },
  {
    slug: "passenger-announcement-system",
    name: "Passenger Announcement System",
    status: "Coming in Phases",
    category: "Audio Media",
    bestUse: "Audio recall in passenger movement zones and transit environments.",
    reporting: "Campaign execution reports where applicable.",
  },
  {
    slug: "bus-panels",
    name: "Bus Panels",
    status: "Coming in Phases",
    category: "Bus Media",
    quantity: CLIENT_FACTS.buses,
    bestUse: "Route-level outdoor exposure across moving bus inventory.",
    reporting: "GPS-enabled installation proof and depot-wise visibility proof.",
  },
  {
    slug: "low-sound-video",
    name: "Low Sound Video via LCD/LED Display",
    status: "Coming in Phases",
    category: "Digital Media",
    bestUse: "Low-sound motion communication in controlled passenger environments.",
    reporting: "Digital screen logs and execution reports where applicable.",
  },
  {
    slug: "glow-sign-boards",
    name: "Glow Sign Boards",
    status: "Coming in Phases",
    category: "Station Media",
    bestUse: "Branded station visibility where approved for this media format.",
    reporting: "Installation proof and campaign execution reports.",
  },
  {
    slug: "station-boards-sign-boards",
    name: "Station Boards / Sign Boards",
    status: "Live Now",
    category: "Station Media",
    bestUse: "Non-lit station signage visibility for station-level awareness.",
    reporting: "GPS-enabled start photos, end photos, and installation proof.",
    note: "Station Boards are non-lit.",
  },
] as const;
