// 36 districts of Maharashtra with approximate normalized coords
// (x,y in 0–100 range over a stylized Maharashtra bounding box).
export type District = { name: string; x: number; y: number };

export const MAHARASHTRA_DISTRICTS: District[] = [
  { name: "Mumbai City", x: 14, y: 62 },
  { name: "Mumbai Suburban", x: 15, y: 60 },
  { name: "Thane", x: 18, y: 56 },
  { name: "Palghar", x: 14, y: 50 },
  { name: "Raigad", x: 19, y: 67 },
  { name: "Ratnagiri", x: 22, y: 78 },
  { name: "Sindhudurg", x: 23, y: 90 },
  { name: "Pune", x: 28, y: 66 },
  { name: "Satara", x: 30, y: 75 },
  { name: "Sangli", x: 34, y: 82 },
  { name: "Kolhapur", x: 30, y: 87 },
  { name: "Solapur", x: 42, y: 76 },
  { name: "Nashik", x: 26, y: 46 },
  { name: "Dhule", x: 30, y: 36 },
  { name: "Nandurbar", x: 24, y: 30 },
  { name: "Jalgaon", x: 38, y: 36 },
  { name: "Ahmednagar", x: 34, y: 60 },
  { name: "Ch. Sambhajinagar", x: 42, y: 50 },
  { name: "Jalna", x: 47, y: 50 },
  { name: "Beed", x: 47, y: 62 },
  { name: "Dharashiv", x: 50, y: 72 },
  { name: "Latur", x: 55, y: 70 },
  { name: "Parbhani", x: 53, y: 56 },
  { name: "Hingoli", x: 56, y: 50 },
  { name: "Nanded", x: 60, y: 60 },
  { name: "Buldhana", x: 46, y: 40 },
  { name: "Akola", x: 53, y: 40 },
  { name: "Washim", x: 56, y: 46 },
  { name: "Amravati", x: 60, y: 36 },
  { name: "Yavatmal", x: 64, y: 50 },
  { name: "Wardha", x: 70, y: 44 },
  { name: "Nagpur", x: 74, y: 36 },
  { name: "Bhandara", x: 80, y: 36 },
  { name: "Gondia", x: 86, y: 32 },
  { name: "Chandrapur", x: 78, y: 50 },
  { name: "Gadchiroli", x: 86, y: 50 },
];
